#!/bin/bash
# SnapBack Installer
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/snapback"
CLAUDE_SETTINGS="$HOME/.claude/settings.json"

# Default values
BROWSER="Google Chrome"
FOCUS_APPS=("Cursor" "Ghostty")

echo "╔══════════════════════════════════════╗"
echo "║         SnapBack Installer           ║"
echo "╚══════════════════════════════════════╝"
echo ""

# Check for required tools
if ! command -v osascript &>/dev/null; then
  echo "❌ Error: osascript not found. SnapBack requires macOS."
  exit 1
fi

# Check for existing config
if [[ -f "$CONFIG_DIR/config" ]]; then
  echo "📁 Existing config found at $CONFIG_DIR/config"
  echo ""
  echo "Options:"
  echo "  1) Keep existing config (just update scripts/hooks)"
  echo "  2) Reconfigure (overwrite with new settings)"
  read -p "Choose [1]: " config_choice
  config_choice="${config_choice:-1}"

  if [[ "$config_choice" == "1" ]]; then
    echo "✅ Keeping existing config"
    # Load existing config for permission message
    source "$CONFIG_DIR/config"
    skip_config=true
  else
    skip_config=false
  fi
else
  skip_config=false
fi

if [[ "$skip_config" == "false" ]]; then
  # Interactive configuration
  echo ""
  echo "📋 Configuration"
  echo "────────────────"
  echo ""

  # Focus apps
  echo "Which apps should SnapBack focus when Claude needs attention?"
  echo "(These will be activated in order, last one stays on top)"
  echo ""
  echo "Default: Cursor,Ghostty (press Enter to accept)"
  read -p "> " focus_apps_input
  focus_apps_input="${focus_apps_input:-Cursor,Ghostty}"
  if [[ -z "$focus_apps_input" ]]; then
    focus_apps_input="Cursor,Ghostty"
  fi
  IFS=',' read -ra FOCUS_APPS_ARR <<< "$focus_apps_input"

  # Focus delay
  echo ""
  echo "How long to wait between focusing each app?"
  echo "(Increase if apps don't focus properly on slower machines)"
  echo ""
  echo "Default: 0.5 seconds (press Enter to accept)"
  read -p "> " focus_delay
  focus_delay="${focus_delay:-0.5}"

  # Browser
  echo ""
  echo "Which browser should SnapBack control for media pause/resume?"
  echo ""
  echo "Default: Google Chrome (press Enter to accept)"
  read -p "> " browser
  browser="${browser:-Google Chrome}"

  # Seek back
  echo ""
  echo "When resuming video, how many seconds should it rewind?"
  echo "(So you don't miss what was said right before the pause)"
  echo ""
  echo "Default: 1 second (press Enter to accept)"
  read -p "> " seek_back
  seek_back="${seek_back:-1}"

  # Throttle
  echo ""
  echo "Minimum time between triggers (prevents rapid repeated notifications)"
  echo ""
  echo "Default: 2 seconds (press Enter to accept)"
  read -p "> " throttle
  throttle="${throttle:-2}"

  # Notification sound
  echo ""
  echo "What sound should play when Claude needs attention?"
  echo ""
  echo "  1) Default - bundled notification sound (press Enter to accept)"
  echo "  2) None - silent mode"
  echo "  3) Custom - provide path to your own .mp3 file"
  echo ""
  read -p "> " sound_choice
  sound_choice="${sound_choice:-1}"

  case "$sound_choice" in
    2) notification_sound="" ;;
    3)
      read -p "Path to .mp3 file: " notification_sound
      ;;
    *) notification_sound="default" ;;
  esac

  echo ""
  echo "📁 Creating config directory..."
  mkdir -p "$CONFIG_DIR"

  # Build FOCUS_APPS array string
  focus_apps_str="("
  for app in "${FOCUS_APPS_ARR[@]}"; do
    app=$(echo "$app" | xargs)  # trim whitespace
    focus_apps_str+="\"$app\" "
  done
  focus_apps_str="${focus_apps_str% })"

  # Write config
  cat > "$CONFIG_DIR/config" <<EOF
# SnapBack Configuration
# Generated by install.sh

FOCUS_APPS=$focus_apps_str
FOCUS_DELAY=$focus_delay
BROWSER="$browser"
SEEK_BACK_SECONDS=$seek_back
THROTTLE_SECONDS=$throttle
NOTIFICATION_SOUND="$notification_sound"
EOF

  echo "✅ Config saved to $CONFIG_DIR/config"
fi

# Make scripts executable
chmod +x "$SCRIPT_DIR/snapback.sh"
chmod +x "$SCRIPT_DIR/snapback-resume.sh"
echo "✅ Scripts made executable"

# Claude Code integration
echo ""
echo "🔗 Claude Code Integration"
echo "──────────────────────────"

if [[ -f "$CLAUDE_SETTINGS" ]]; then
  echo "Found existing Claude settings at $CLAUDE_SETTINGS"
  read -p "Add SnapBack hooks to Claude Code? [Y/n]: " add_hooks
  add_hooks="${add_hooks:-Y}"
else
  echo "No Claude settings found at $CLAUDE_SETTINGS"
  read -p "Create Claude settings with SnapBack hooks? [Y/n]: " add_hooks
  add_hooks="${add_hooks:-Y}"
fi

if [[ "$add_hooks" =~ ^[Yy]([Ee][Ss])?$ || -z "$add_hooks" ]]; then
  mkdir -p "$(dirname "$CLAUDE_SETTINGS")"

  # Check if jq is available for proper JSON manipulation
  if command -v jq &>/dev/null; then
    if [[ -f "$CLAUDE_SETTINGS" ]]; then
      # Merge hooks into existing settings
      tmp=$(mktemp)
      jq --arg snapback "$SCRIPT_DIR/snapback.sh" --arg resume "$SCRIPT_DIR/snapback-resume.sh" '
        .hooks.PermissionRequest = [{"matcher": "*", "hooks": [{"type": "command", "command": $snapback}]}] |
        .hooks.Stop = [{"hooks": [{"type": "command", "command": $snapback}]}] |
        .hooks.PostToolUse = ((.hooks.PostToolUse // []) | map(select(.matcher != "Edit|Write|Bash"))) + [{"matcher": "Edit|Write|Bash", "hooks": [{"type": "command", "command": $resume}]}] |
        .hooks.UserPromptSubmit = [{"hooks": [{"type": "command", "command": $resume}]}]
      ' "$CLAUDE_SETTINGS" > "$tmp" && mv "$tmp" "$CLAUDE_SETTINGS"
    else
      # Create new settings file
      jq -n --arg snapback "$SCRIPT_DIR/snapback.sh" --arg resume "$SCRIPT_DIR/snapback-resume.sh" '{
        hooks: {
          PermissionRequest: [{"matcher": "*", "hooks": [{"type": "command", "command": $snapback}]}],
          Stop: [{"hooks": [{"type": "command", "command": $snapback}]}],
          PostToolUse: [{"matcher": "Edit|Write|Bash", "hooks": [{"type": "command", "command": $resume}]}],
          UserPromptSubmit: [{"hooks": [{"type": "command", "command": $resume}]}]
        }
      }' > "$CLAUDE_SETTINGS"
    fi
    echo "✅ Claude Code hooks configured"
  else
    echo ""
    echo "⚠️  jq not found. Please manually add these hooks to $CLAUDE_SETTINGS:"
    echo ""
    cat <<EOF
{
  "hooks": {
    "PermissionRequest": [
      {"matcher": "*", "hooks": [{"type": "command", "command": "$SCRIPT_DIR/snapback.sh"}]}
    ],
    "Stop": [
      {"hooks": [{"type": "command", "command": "$SCRIPT_DIR/snapback.sh"}]}
    ],
    "PostToolUse": [
      {"matcher": "Edit|Write|Bash", "hooks": [{"type": "command", "command": "$SCRIPT_DIR/snapback-resume.sh"}]}
    ],
    "UserPromptSubmit": [
      {"hooks": [{"type": "command", "command": "$SCRIPT_DIR/snapback-resume.sh"}]}
    ]
  }
}
EOF
  fi
else
  echo "⏭️  Skipping Claude Code integration"
fi

# Grant permissions
echo ""
echo "🔐 Permissions"
echo "──────────────"
echo "Running scripts once to trigger macOS permission dialogs..."
echo "(You may need to grant access to System Events and $BROWSER)"
echo ""

"$SCRIPT_DIR/snapback.sh" || true

echo ""
echo "╔══════════════════════════════════════╗"
echo "║      ✅ Installation Complete!       ║"
echo "╚══════════════════════════════════════╝"
echo ""
echo "Config: $CONFIG_DIR/config"
echo "Scripts: $SCRIPT_DIR/snapback.sh"
echo "         $SCRIPT_DIR/snapback-resume.sh"
echo ""
echo "Restart Claude Code to apply hooks."
